### ISSUE TITLE
Audio fails to upload when manifest specifies 1 image + 1 audio file per subject

### ISSUE THREAD

**Issue by hughdickinson** [zooniverse/panoptes-cli#152]
## Actions:

Running:
```
$  panoptes subject-set create 10969 "HughTestingCLI"
80250 HughTestingCLI
$ panoptes subject-set upload-subjects 80250 manifest.csv
```
Using this [manifest file](https://github.com/zooniverse/panoptes-cli/files/4193663/manifest.txt) and running from a directory that contains the manifest file and all the files specified within it. 

## Expected Result:

Creation of a new subject set containing five subjects with image and audio components that will render appropriately in the PFE subject viewer. 

## Actual Result:

The CLI runs and exits with no errors. The subject set `HughTestingCLI` is created as are 5 subjects within it, but they only include the image component. It seems like the audio component is not uploaded and/or not added to the list of subject locations.

## Extra Info:

Output of `panoptes info`:
```
Panoptes CLI version: 1.1.1
Panoptes client version: 1.1.1
Operating system: Darwin 19.2.0
API endpoint: https://www.zooniverse.org
Click: 7.0
PyYAML: 5.1.2
Python version: 3.7.5
libmagic: 0.4.15
```

**Comment by camallen** [comment]
This is an incoming request payload for a subject creation request, note only 1 locations mime type here. Something to do with different mime types for multi media resource subjects?
```
{
    "subjects": {
        "links": {
            "project": "10969"
        },
        "locations": [
            "image/jpeg"
        ],
        "metadata": {
            " Full audio": " [Link to full audio](+tab+https://drive.google.com/open?id=13LsOrPiMNIvY5p4iYui2Erm_Wj1jIHvB)",
            " filename_2": " cut_2.mp3",
            "filename_1": "image.jpeg"
        }
    }
}
```

**Comment by hughdickinson** [comment]
Examining @camallen's comment I see that the issue is extra whitespace prepended to the audio file path. The manifest CSV contained spaces after the commas that were not stripped. A properly formatted manifest fixes this issue. Closing.
