### ISSUE TITLE
CSV reader for parsing manifests does not ignore whitespace

### ISSUE THREAD

**Issue by hughdickinson** [zooniverse/panoptes-cli#153]
The instance of `csv.reader` created [here](https://github.com/zooniverse/panoptes-cli/blob/55957452b2c461b7a69d8882bc5dab7244d13510/panoptes_cli/commands/subject_set.py#L303) does not ignore any trailing whitespace following the delimiting `,` characters. In manifests that specify multiple file locations or when the file location is not in the zeroth column, then this will cause the file validation method to fail because the full string (including whitespace) is considered when searching for a matching file path.

**Comment by hughdickinson** [comment]
A potential solution for this is to add:
```python
skipinitialspace=True
```
to the arguments of `csv.reader`.

**Comment by lcjohnso** [comment]
Closed by #154
