### ISSUE TITLE
-q / --quiet switch for create subject set

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/panoptes-cli#156]
I'm doing a bit of shell scripting with the CLI, and for scripting subject set creation and subject linking a `-q` switch for subject set creation would be useful (saves me from doing some `cut`ting).

Happy for me to submit a PR?

**Comment by adammcmaster** [comment]
Sure, a PR would be welcome! If you don't mind, it's probably useful to add the same thing to all the create commands rather than just subject set.
