### ISSUE TITLE
command to link subject sets to workflows

### ISSUE THREAD

**Issue by plorch** [zooniverse/panoptes-cli#16]
On project 1793 we now have more subject sets than can fit on one page of the Project Builder Workflow page under associated subject sets.  I had to get help linking sets.  It would be nice to have a command to link sets to workflows.

**Comment by astopy** [comment]
Thanks for the suggestion, that's a good idea!

**Comment by plorch** [comment]
Thank Cam Allen, who suggested I submit it. The python client can already do it. 

Patrick Lorch

Manager of field research
2277 West Ridgewood Drive
Parma, OH 44134
pdl@clevelandmetroparks.com
clevelandmetroparks.com
