### ISSUE TITLE
PyPI version blocked by old PyYAML requirement

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/panoptes-cli#166]
I see this fixed in master, but the currently available version on PyPI is not accepting my up-to-date PyYAML 5.3.1 and instead tries to install version 5.1.2.

No problem with installing your GH master.

**Comment by adammcmaster** [comment]
Thanks, I'll put out a new release to bump the PyYAML version this week.

**Comment by michaelaye** [comment]
if you are the only maintainer, I'm happy to support you with this package?

**Comment by adammcmaster** [comment]
Thanks for the offer! I'm the only one maintaining this at the moment but we'll probably be looking to get more people involved soon, so we'll keep you in mind.

The new release will be available on Pypi shortly.

**Comment by lcjohnso** [comment]
Closed by v1.1.2 via #170
