### ISSUE TITLE
Warn user if client version is outdated

### ISSUE THREAD

**Issue by claybarrett** [zooniverse/panoptes-cli#201]
Last week uploaded a batch of images to a subject set using 1.1.1. The resultant load message was the same as before (Uploading Subjects > 100%) . However, the images would not appear during classification or in the subject_set viewer. The fix was to update panoptes to 1.1.3, and then load subjects to a new subject set.

My request is that if a client is outdated and the upload is not going to successfully load subjects, warn the user to update the client instead of continuing the upload process.

**Comment by jebyrnes** [comment]
Having this problem as well - but, when I try to update, I get 

ERROR: panoptes 0.3.0 has requirement PyYAML==3.13, but you'll have pyyaml 5.3.1 which is incompatible.

Any thoughts?

**Comment by claybarrett** [comment]
I'm not sure what you are using to update, I used `pip install -U panoptes-client`. If you still get this error, I would guess you have some other package that depends on the newer version of PyYaml, or otherwise have it locked to that version. I would try making a fresh venv just for Panoptes and install fresh to see if that resolves the issue..

**Comment by camallen** [comment]
> Last week uploaded a batch of images to a subject set using 1.1.1. The resultant load message was the same as before (Uploading Subjects > 100%) . However, the images would not appear during classification or in the subject_set viewer. The fix was to update panoptes to 1.1.3, and then load subjects to a new subject set.
> 
> My request is that if a client is outdated and the upload is not going to successfully load subjects, warn the user to update the client instead of continuing the upload process.

We've looked into this in the underlying client code, https://github.com/zooniverse/panoptes-python-client/issues/254

Sadly we can't retroactively add this feature to existing clients in the wild but it's something we will look to add in the future.
