### ISSUE TITLE
README.md edits

### ISSUE THREAD

**Issue by plorch** [zooniverse/panoptes-cli#32]
I am starting to use the new command line tools after having used the client software and have some suggestions.

- Make clear under installations that the two steps are alternatives.  Both are not needed, as far as I can tell.  If you have pip and not git the second one will fail.
- Explain what an endpoint is and why you might not use the default (developers only?).
- document the ls command
  panoptes subject_set ls --project-id 2797
  or
  panoptes subject_set ls --project-id 2797 9488
- add how to use modify to change subject set names
  panoptes subject_set modify --subject-set-id 9509 --display-name C8_WC3732b

**Comment by astopy** [comment]
Thanks for the suggestions!
