### ISSUE TITLE
Speeding up multiple requests

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/panoptes-cli#4]
@astopy I'm very much a python noob, but so not sure exactly how to do this, but I think the multiple requests for getting e.g. subject set data are running in series. Can we get them to run in parallel? I thought [`map()` from multiprocessing](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.pool.multiprocessing.Pool.map) would do it, but I can't get it working...

**Comment by astopy** [comment]
I would have thought `map` would do it. Want to put what you have so far in a branch and I’ll take a look?

**Comment by CKrawczyk** [comment]
`map()` would be my first guess too.  Although one thing to watch out for with multiprocessing in python is that the function being run must be [picklabe](https://docs.python.org/2/library/pickle.html).

**Comment by rogerhutchings** [comment]
I got an error along those lines @CKrawczyk... I'll push it up later on

**Comment by rogerhutchings** [comment]
Here we go: https://github.com/zooniverse/panoptes-cli/blob/parallel/panoptes_cli/scripts/panoptes.py

I'm probably doing something that's totally obviously wrong

**Comment by CKrawczyk** [comment]
Any function or class that used my `map()` must be defined at the top level of the program (or it can't be pickled), so try moving 
```python
def get_collaborator (...):
```
above 
```python
def project (...):
```

**Comment by rogerhutchings** [comment]
No joy, unfortunately - I think the function definition immediately after `command()` has to be for the cli function itself...

**Comment by CKrawczyk** [comment]
Not sure if will help, but you can "trick" python into pickling your file by taking any non-top level function and placing them in a top-level wrapper similar to the one used here: https://github.com/dfm/emcee/blob/master/emcee/ensemble.py#L492-L514

```python
class _function_wrapper(object):
    def __init__(self, f, args, kwargs):
        self.f = f
        self.args = args
        self.kwargs = kwargs

    def __call__(self, x):
        try:
            return self.f(x, *self.args, **self.kwargs)
        except:
            import traceback
            print("Exception while calling your function:")
            print("  params:", x)
            print("  args:", self.args)
            print("  kwargs:", self.kwargs)
            print("  exception:")
            traceback.print_exc()
            raise
```

**Comment by CKrawczyk** [comment]
Also lambda functions can't be in `map()` but you can use a wrapper like the one above to make it work.  See: http://stackoverflow.com/questions/4827432/how-to-let-pool-map-take-a-lambda-function

**Comment by astopy** [comment]
Closing this for now. We can come back to this if speed becomes a problem in the future.
