### ISSUE TITLE
Update regex to match mp3s and mp4s

### ISSUE THREAD

**Issue by trouille** [zooniverse/panoptes-cli#54]
When trying to run the command:

>panoptes subject-set upload-subjects 14534 manifest.csv

I get the error:

Could not find any files in row:
1,56b1dc3f8f753200018efbb6-use.mp4,red-River,10-2-15

same error with mp3

In Slack #dev thread https://zooniverse.slack.com/archives/C06DCM0V9/p1504298734000346, we think all that is needed is to update the regex to match these file types.

**Comment by srallen** [comment]
We should also add `txt` as a recognized file type since there are projects in the pipeline that use text subjects.

**Comment by astopy** [comment]
I may just get rid of that regex entirely and rely on the API to validate file types.
