### ISSUE TITLE
Libmagic detection not working 

### ISSUE THREAD

**Issue by celdermire** [zooniverse/panoptes-cli#64]
@astopy 
Tried checking for libmagic using the 

`$ panoptes info
`
command, but all I get is 

```
$ panoptes info
Usage: panoptes [OPTIONS] COMMAND [ARGS]...

Error: No such command "info".
$ 
```
Went ahead and Installed from git in case it hadn't been integrated into the production Panoptes client, but that didn't improve things either. 

Thanks!

**Comment by astopy** [comment]
You're right that the info command isn't in the production version yet. I should clarify the README, because to install from GitHub you'll probably need the `-U` option if you already have the CLI installed:

```
pip install -U git+git://github.com/zooniverse/panoptes-cli.git
```

**Comment by celdermire** [comment]
That did it—thanks!
