### ISSUE TITLE
Which version of python does this run with?

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-cli#66]
I don't know but i assume both 2/3, but we should probably clarify it. 

I couldn't see it in the docs and I assume people getting started may not know what `pip install` is / does from the https://github.com/zooniverse/panoptes-cli#installation instructions. 

Should we mention you'll need python installed at the start of this section or a new Dependencies section?

**Comment by astopy** [comment]
I'll be working on the documentation for this soon ahead of the 1.0 release, so I'll take care of this then (but yes, it both versions of Python are supported).

**Comment by camallen** [comment]
thanks for the response and good to know.
