### ISSUE TITLE
Cmd to get an oauth token for the authenticated credentials

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-cli#89]
Some services require the use of an oauth token. Ideally our recommended tooling (python client / cli) would provide a way to get a valid oauth token for use across systems. 

I myself would find this incredibly useful when manually interacting with the APIs as well. 

Would a PR supporting this be accepted? I'd be happy to spike on this and any direction would be appreciated.

**Comment by adammcmaster** [comment]
Yeah, I can see that being useful. The client can probably already return a token (though it won't be documented at the moment), and actually it would be good to switch the CLI to using tokens rather than permanently storing the password so this could be a first step towards that.

**Comment by mwalmsley** [comment]
Just to say that recently I needed a token for Caesar and, while it wasn't that complicated to get the token via dev tools, how to do so wasn't documented and that would have been a problem without Slack. `token = Panoptes.get_token()` would have been really handy for me!
