### ISSUE TITLE
504 error cancels upload 

### ISSUE THREAD

**Issue by denslowm** [zooniverse/panoptes-cli#90]
This has been a issue for a few weeks now. When I upload a subject set I have to try multiple times because of 504 errors.

I update panoptes-cli every session so I should have the most current version. 

I am using the following command:

panoptes subject-set upload-subjects 61052 e1a729e9-b30e-46aa-9d98-3e134453bdd8-ascii.csv 

Yesterday I tried this same subject set 4 times. Each time it failed at a different point. 5%, 58%, 64%, 37%. It takes several hours to discover this each time. Here is an example error message:

Error: Could not save subject in row 1878
The API returned error: Received HTTP status code 504 from API

To be clear, the subject is different each time so it doesn't appear to be an issue with a specific subject that is being loaded. What is the best way to deal with this? Is there a way to restart the upload from where it failed? Is there a reason that this command has become more sensitive to 504 errors recently?

As an aside, this is a big/urgent issue for the Notes from Nature team because we must use the CLI for any manifest that has ".jpg" is any column other than the subject name column. These kinds of subjects sets can't be loaded via the Project Builder (a known issue).

**Comment by camallen** [comment]
I was also running into this problem a while back and I believe this is linked to https://github.com/zooniverse/panoptes-python-client/pull/189. that fix hasn't been released as a published version yet so updating normally won't include it. 

Manually updating to the github version of the panoptes python client dependency `pip install -U git+git://github.com/zooniverse/panoptes-python-client.git` should solve your problems. 

Could you try upgrading via the github link above and report back?

**Comment by denslowm** [comment]
I updated as you suggested and I am running the upload again.

I get the following message:
No handlers could be found for logger "panoptes_client"

Should I be concerned? It does appear to be uploading subjects.

**Comment by denslowm** [comment]
The upload just finished. It contained 4,993 subjects. It appears that the new version may fix the issue.

**Comment by adammcmaster** [comment]
Great, I'm glad you got it to upload. I'll close this now, but could you open another issue if the logging error persists?
