### ISSUE TITLE
bash: panoptes: command not found

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [zooniverse/panoptes-cli#91]
When I follow the installation procedure step by step, after installing panoptescli back at the command line interface, typing panoptes configure or other commands simply result in: 
bash: panoptes: command not found

System: Debian, all packages up to date

any advise?
Philipp | SPOTTERON

**Comment by adammcmaster** [comment]
I see @camallen [answered this on Talk](https://www.zooniverse.org/talk/17/857224) so I'll close this now.
