### ISSUE TITLE
Better character set support

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [zooniverse/panoptes-cli#92]
When using panoptes on Linux (Debian Stretch)  to upload files via a manifest.csv,
the commandline exits with ehe following error:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

We tried to remove all special characters in the csv file (since it is a German based project, that would be not ideal but doable) and tried different encodings of the CSV file - but nothing really worked.
The standard encoding is: UTF-8

Any advise?
Thanks!
Philipp | SPOTTERON

**Comment by PhilippSPOTTERON** [comment]
@denslowm thanks a lot, that helped and the files are uploading now -  I ll check when it is finished if there are issues with special characters and report back again.

**Comment by PhilippSPOTTERON** [comment]
Sadly that seems to kill the special characters like ü, ä or ö:
the result in the Metadata is: "Wildpark Nordgatter H?tte 5" - It should be: "Wildpark Nordgatter H**ü**tte 5"

For now we will apply the workaround to rewrite all special characters, but the Zooniverse tools should definatly have better multi-language support.

**Comment by adammcmaster** [comment]
We'll definitely look into improving this in a future version.

**Comment by adammcmaster** [comment]
I've been experimenting with this a bit, and it only seems to be a problem in Python 2. It works perfectly in Python 3.

Python 2 will reach it's end of life in January, and while I'm aware that a lot of people will still be using Python 2 after that date I think the most feasible solution is to recommend that people use a newer version of Python if they need unicode support.
