### ISSUE TITLE
Add a project info command

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-cli#99]
Allow the project resource details to be fetched via something like `panoptes project info PROJECT_ID`

**Comment by adammcmaster** [comment]
Which details would this display?

**Comment by camallen** [comment]
Any number of these attributes, may be all of them?
```
    :id, :display_name, :classifications_count,
    :subjects_count, :created_at, :updated_at, :available_languages,
    :title, :description, :introduction, :private, :retired_subjects_count,
    :configuration, :live, :urls, :migrated, :classifiers_count, :slug, :redirect,
    :beta_requested, :beta_approved, :launch_requested, :launch_approved, :launch_date,
    :href, :workflow_description, :primary_language, :tags, :experimental_tools,
    :completeness, :activity, :state, :researcher_quote, :mobile_friendly, :featured
```

https://github.com/zooniverse/Panoptes/blob/576607c1469d8c2a89fa0b20a3eabd993bc9e252/app/serializers/project_serializer.rb#L12

**Comment by camallen** [comment]
My use case today was to find out how many subjects each launch approved project had. I could get the list of launched project ids but couldn't get any details for each of the individual projects.

**Comment by adammcmaster** [comment]
OK, so basically print all the attributes in a human-readable way. It'd probably be useful to add something like this for all objects rather than just projects.
